author: Anton Vlezko
output: public
swift_build_tool: xcodebuild
theme: jony
build_tool_arguments:
  - -scheme
  - GXTextField
  - -sdk
  - iphoneos
  - -destination,platform=iOS Simulator,OS=latest,name=iPhone 11 Pro
